# Credits to jeanconn for the package https://binstar.org/jeanconn/fftw
package:
    name: hypercube
    version: "0.0.2"

source:
    git_url: http://cees-gitlab.Stanford.EDU/bob/hypercube.git

requirements:
    build:
      - cmake
      - pybind11
    run:
      - python


# Note: tests are run when building the package, they are not accessible
# in the installed package.

about:
    home: http://cees-gitlab.Stanford.EDU/bob/hypercube
    license: BSD
    summary: 'Library for dealing with regular cubes'
